import os

# --- FINNHUB CONFIGURATION ---
FINNHUB_API_TOKEN = os.getenv("FINNHUB_API_TOKEN")

# --- DANH SÁCH ---
FINNHUB_TICKERS = [
    "BINANCE:BTCUSDT", "BINANCE:ETHUSDT", "BINANCE:SOLUSDT", "BINANCE:BNBUSDT",
    "BINANCE:XRPUSDT", "BINANCE:ADAUSDT", "BINANCE:DOGEUSDT", "BINANCE:AVAXUSDT",
    "BINANCE:DOTUSDT", "BINANCE:MATICUSDT", "BINANCE:LTCUSDT", "BINANCE:LINKUSDT",
    "BINANCE:SHIBUSDT", "BINANCE:TRXUSDT", "BINANCE:ATOMUSDT", "BINANCE:UNIUSDT"
]

# --- KAFKA CONFIGURATION ---
KAFKA_SERVER = os.getenv("KAFKA_SERVER", "kafka:9092")
KAFKA_TOPIC = os.getenv("KAFKA_TOPIC", "stock-ticks")